# Generated by Django 4.2.27 on 2025-12-22 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_usuario_numero_vivienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Votación')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha límite para votar')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votaciones', to='usuarios.cooperativa')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100, verbose_name='Opción (ej: Sí, No, Abstención)')),
                ('votos_cantidad', models.PositiveIntegerField(default=0, verbose_name='Contador de votos')),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='votaciones.votacion')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
                ('opcion_elegida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votaciones.opcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_emitidos', to=settings.AUTH_USER_MODEL)),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_totales', to='votaciones.votacion')),
            ],
            options={
                'unique_together': {('usuario', 'votacion')},
            },
        ),
    ]
