# Generated by Django 4.2.27 on 2025-12-25 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votacion',
            name='activa',
        ),
        migrations.AddField(
            model_name='votacion',
            name='votos_totales',
            field=models.ManyToManyField(related_name='votos_emitidos', through='votaciones.Voto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='texto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='votos_cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='fecha_fin',
            field=models.DateTimeField(verbose_name='Fecha y hora de cierre'),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título de la votación'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voto',
            name='votacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votaciones.votacion'),
        ),
    ]
