# Generated by Django 4.2.27 on 2025-12-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero_vivienda',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nº Vivienda/Piso'),
        ),
    ]
