# Generated by Django 4.2.27 on 2025-12-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_numero_vivienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativa',
            name='presidente_ve_votos',
            field=models.BooleanField(default=False, verbose_name='¿El Presidente puede ver quién votó qué?'),
        ),
    ]
